-- =============================================================================
-- Migration 012: User suspended flag + system config table
-- Safe: additive only
-- =============================================================================

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS is_suspended  BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS suspended_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS suspended_by  VARCHAR(36) REFERENCES users(id),
    ADD COLUMN IF NOT EXISTS suspend_reason VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_users_suspended
    ON users(is_suspended) WHERE is_suspended = true;

-- System config table (key-value store for admin toggles)
CREATE TABLE IF NOT EXISTS system_config (
    key         VARCHAR(100) PRIMARY KEY,
    value       TEXT NOT NULL,
    description VARCHAR(255),
    updated_by  VARCHAR(36) REFERENCES users(id),
    updated_at  TIMESTAMPTZ DEFAULT now()
);

-- Seed default config values
INSERT INTO system_config (key, value, description) VALUES
('maintenance_mode',      'false', 'Global maintenance mode — blocks all job creation'),
('elevenlabs_enabled',    'true',  'ElevenLabs kill switch — disables all cloning if false'),
('concurrency_cap',       '2',     'Max active task weight (overrides Redis cap at runtime)'),
('beta_registrations',    'true',  'Allow new beta signups'),
('watermark_text',        'Generated by VoxTN Online.', 'Watermark audio text')
ON CONFLICT (key) DO NOTHING;
